### ISSUE TITLE
Random grab-bag of ideas

### ISSUE THREAD

**Issue by Zireael07** [Bladesodoom1895/textrpg#12]
- [x] allow 'n' 's' 'e' 'w' input instead of 'north', 'south' etc. (Hint: this can be easily hardcoded, just check for 'n' or 's' in input...)
- [x] strip whitespace (i.e. spaces/linefeeds) and punctuation (commas, dot) from player answer when answering a riddle
- [x] similar to the above, convert to lowercase when checking (Hint: you can do both those things with built-in Python functions)

**Comment by Bladesodoom1895** [comment]
most answers have spaces in them, so why would I want to remove the whitespace between words?

**Comment by Bladesodoom1895** [comment]
I believe I have done all of the things you have suggested.

**Comment by Zireael07** [comment]
I meant whitespace at beginning/end, not between words ;)
