### ISSUE TITLE
Some functions call themselves

### ISSUE THREAD

**Issue by Midnex** [Bladesodoom1895/textrpg#18]
Some functions call themselves, you should never call a the same function within the same function.

For example title_screen_selections calls itself if the user doesn't make a valid selection. You should use a while look to ensure the only enters what you want them to.

This can be seen in the following functions as well
prompt, player_move, player_look, and riddles. 

In the case of title screen you can remove `title_screen_selections()` from the last line, as if the user does not enter the right selection it will simply repeat the title_screen_selection function.

**Comment by Bladesodoom1895** [comment]
I do believe all of these have been fixed.
